# frozen_string_literal: true

module Stupidedi
  module Schema
    module Generation
      # Generates an optional master loader (e.g. edi.rb) that requires the whole
      # generated tree in dependency order, so a non-Rails consumer can pull in
      # the entire grammar with a single `require "edi"`. Like the registration
      # generator it scans the output directory, so it must run last.
      #
      # Not emitted by default - it adds a file the Rails-autoloaded layout does
      # not need. Pass master_loader: true (or --master-loader) to include it.
      class MasterLoaderGenerator
        include Support

        def initialize(out:, namespace: "Edi")
          @out = out
          @namespace = namespace
        end

        def generate
          build_ruby_content
        end

        def output_path
          "#{namespace_path}.rb"
        end

        private

        attr_reader :out

        def root
          File.join(out, namespace_path)
        end

        def version_dirs
          Dir.glob(File.join(root, "*"))
            .select { |p| File.directory?(p) && VERSION_MODULES.value?(camelize(File.basename(p))) }
            .sort
        end

        def require_lines
          lines = []

          # Version loaders first - they set up the per-version autoloads that the
          # interchange and standards files (and the registration) depend on.
          version_dirs.each do |dir|
            lines << require_line("#{namespace_path}/#{File.basename(dir)}")
          end

          # Interchange envelopes.
          Dir.glob(File.join(root, "interchanges", "*.rb")).sort.each do |file|
            lines << require_line("#{namespace_path}/interchanges/#{File.basename(file, '.rb')}")
          end

          # Transaction-set standards.
          version_dirs.each do |dir|
            base = File.basename(dir)
            Dir.glob(File.join(dir, "standards", "*.rb")).sort.each do |file|
              lines << require_line("#{namespace_path}/#{base}/standards/#{File.basename(file, '.rb')}")
            end
          end

          # Registration last.
          registration = File.join(root, "stupidedi_registration.rb")
          lines << require_line("#{namespace_path}/stupidedi_registration") if File.exist?(registration)

          lines
        end

        def require_line(path)
          %(require "#{path}")
        end

        def build_ruby_content
          <<~RUBY
            # frozen_string_literal: true

            # Auto-generated by Stupidedi::Schema::Generation::MasterLoaderGenerator
            # Requires the full generated grammar tree in dependency order.
            require "tediparse"

            #{require_lines.join("\n")}
          RUBY
        end
      end
    end
  end
end
