# frozen_string_literal: true

module Stupidedi
  module Schema
    module Generation
      # Generates an optional master loader (e.g. edi.rb) that requires the whole
      # generated tree in dependency order, so a non-Rails consumer can pull in
      # the entire grammar with a single `require "edi"`.
      #
      # Like the registration generator it is a whole-tree artifact: it scans an
      # ordered list of roots and unions the releases found (earlier roots shadow
      # later ones per release), so a run can scan [staging, out] and require the
      # freshly generated release together with releases already under out.
      #
      # Not emitted by default - it adds a file the Rails-autoloaded layout does
      # not need. Pass master_loader: true (or --master-loader) to include it.
      class MasterLoaderGenerator
        include Support

        # @param roots [String, Array<String>] one or more base directories.
        def initialize(roots:, namespace: "Edi")
          @roots = Array(roots)
          @namespace = namespace
        end

        def generate
          build_ruby_content
        end

        def output_path
          "#{namespace_path}.rb"
        end

        private

        attr_reader :roots

        def namespace_roots
          roots.map { |r| File.join(r, namespace_path) }
        end

        # [[dir_name, version_dir_path], ...] sorted by dir name, each release
        # once, earlier roots shadowing later ones.
        def version_dirs
          seen = {}
          dirs = []
          namespace_roots.each do |base|
            Dir.glob(File.join(base, "*")).each do |dir|
              next unless File.directory?(dir)

              dir_name = File.basename(dir)
              next unless VERSION_MODULES.value?(camelize(dir_name))
              next if seen[dir_name]

              seen[dir_name] = true
              dirs << [dir_name, dir]
            end
          end
          dirs.sort_by(&:first)
        end

        def interchange_basenames
          names = {}
          namespace_roots.each do |base|
            Dir.glob(File.join(base, "interchanges", "*.rb")).each do |path|
              names[File.basename(path, ".rb")] ||= true
            end
          end
          names.keys.sort
        end

        def registration_present?
          namespace_roots.any? { |base| File.exist?(File.join(base, "stupidedi_registration.rb")) }
        end

        def require_lines
          lines = []

          # Version loaders first - they set up the per-version autoloads that the
          # interchange and standards files (and the registration) depend on.
          version_dirs.each do |dir_name, _|
            lines << require_line("#{namespace_path}/#{dir_name}")
          end

          # Interchange envelopes.
          interchange_basenames.each do |basename|
            lines << require_line("#{namespace_path}/interchanges/#{basename}")
          end

          # Transaction-set standards.
          version_dirs.each do |dir_name, dir|
            Dir.glob(File.join(dir, "standards", "*.rb")).sort.each do |file|
              lines << require_line("#{namespace_path}/#{dir_name}/standards/#{File.basename(file, '.rb')}")
            end
          end

          # Registration last.
          lines << require_line("#{namespace_path}/stupidedi_registration") if registration_present?

          lines
        end

        def require_line(path)
          %(require "#{path}")
        end

        def build_ruby_content
          <<~RUBY
            # frozen_string_literal: true

            # Auto-generated by Stupidedi::Schema::Generation::MasterLoaderGenerator
            # Requires the full generated grammar tree in dependency order.
            require "tediparse"

            #{require_lines.join("\n")}
          RUBY
        end
      end
    end
  end
end
